// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.0
// source: proto/api.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShowBgpIpv6SummaryServiceClient is the client API for ShowBgpIpv6SummaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowBgpIpv6SummaryServiceClient interface {
	ShowBgpIpv6Summary(ctx context.Context, in *ShowBgpIpv6SummaryRequest, opts ...grpc.CallOption) (*ShowBgpIpv6SummaryResult, error)
}

type showBgpIpv6SummaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowBgpIpv6SummaryServiceClient(cc grpc.ClientConnInterface) ShowBgpIpv6SummaryServiceClient {
	return &showBgpIpv6SummaryServiceClient{cc}
}

func (c *showBgpIpv6SummaryServiceClient) ShowBgpIpv6Summary(ctx context.Context, in *ShowBgpIpv6SummaryRequest, opts ...grpc.CallOption) (*ShowBgpIpv6SummaryResult, error) {
	out := new(ShowBgpIpv6SummaryResult)
	err := c.cc.Invoke(ctx, "/api.ShowBgpIpv6SummaryService/ShowBgpIpv6Summary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowBgpIpv6SummaryServiceServer is the server API for ShowBgpIpv6SummaryService service.
// All implementations should embed UnimplementedShowBgpIpv6SummaryServiceServer
// for forward compatibility
type ShowBgpIpv6SummaryServiceServer interface {
	ShowBgpIpv6Summary(context.Context, *ShowBgpIpv6SummaryRequest) (*ShowBgpIpv6SummaryResult, error)
}

// UnimplementedShowBgpIpv6SummaryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedShowBgpIpv6SummaryServiceServer struct {
}

func (UnimplementedShowBgpIpv6SummaryServiceServer) ShowBgpIpv6Summary(context.Context, *ShowBgpIpv6SummaryRequest) (*ShowBgpIpv6SummaryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowBgpIpv6Summary not implemented")
}

// UnsafeShowBgpIpv6SummaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowBgpIpv6SummaryServiceServer will
// result in compilation errors.
type UnsafeShowBgpIpv6SummaryServiceServer interface {
	mustEmbedUnimplementedShowBgpIpv6SummaryServiceServer()
}

func RegisterShowBgpIpv6SummaryServiceServer(s grpc.ServiceRegistrar, srv ShowBgpIpv6SummaryServiceServer) {
	s.RegisterService(&ShowBgpIpv6SummaryService_ServiceDesc, srv)
}

func _ShowBgpIpv6SummaryService_ShowBgpIpv6Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowBgpIpv6SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowBgpIpv6SummaryServiceServer).ShowBgpIpv6Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ShowBgpIpv6SummaryService/ShowBgpIpv6Summary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowBgpIpv6SummaryServiceServer).ShowBgpIpv6Summary(ctx, req.(*ShowBgpIpv6SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShowBgpIpv6SummaryService_ServiceDesc is the grpc.ServiceDesc for ShowBgpIpv6SummaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShowBgpIpv6SummaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ShowBgpIpv6SummaryService",
	HandlerType: (*ShowBgpIpv6SummaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowBgpIpv6Summary",
			Handler:    _ShowBgpIpv6SummaryService_ShowBgpIpv6Summary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}

// ShowRouteMapServiceClient is the client API for ShowRouteMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowRouteMapServiceClient interface {
	ShowRouteMap(ctx context.Context, in *ShowRouteMapRequest, opts ...grpc.CallOption) (*ShowRouteMapResult, error)
}

type showRouteMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowRouteMapServiceClient(cc grpc.ClientConnInterface) ShowRouteMapServiceClient {
	return &showRouteMapServiceClient{cc}
}

func (c *showRouteMapServiceClient) ShowRouteMap(ctx context.Context, in *ShowRouteMapRequest, opts ...grpc.CallOption) (*ShowRouteMapResult, error) {
	out := new(ShowRouteMapResult)
	err := c.cc.Invoke(ctx, "/api.ShowRouteMapService/ShowRouteMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowRouteMapServiceServer is the server API for ShowRouteMapService service.
// All implementations should embed UnimplementedShowRouteMapServiceServer
// for forward compatibility
type ShowRouteMapServiceServer interface {
	ShowRouteMap(context.Context, *ShowRouteMapRequest) (*ShowRouteMapResult, error)
}

// UnimplementedShowRouteMapServiceServer should be embedded to have forward compatible implementations.
type UnimplementedShowRouteMapServiceServer struct {
}

func (UnimplementedShowRouteMapServiceServer) ShowRouteMap(context.Context, *ShowRouteMapRequest) (*ShowRouteMapResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowRouteMap not implemented")
}

// UnsafeShowRouteMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowRouteMapServiceServer will
// result in compilation errors.
type UnsafeShowRouteMapServiceServer interface {
	mustEmbedUnimplementedShowRouteMapServiceServer()
}

func RegisterShowRouteMapServiceServer(s grpc.ServiceRegistrar, srv ShowRouteMapServiceServer) {
	s.RegisterService(&ShowRouteMapService_ServiceDesc, srv)
}

func _ShowRouteMapService_ShowRouteMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRouteMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowRouteMapServiceServer).ShowRouteMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ShowRouteMapService/ShowRouteMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowRouteMapServiceServer).ShowRouteMap(ctx, req.(*ShowRouteMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShowRouteMapService_ServiceDesc is the grpc.ServiceDesc for ShowRouteMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShowRouteMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ShowRouteMapService",
	HandlerType: (*ShowRouteMapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowRouteMap",
			Handler:    _ShowRouteMapService_ShowRouteMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
